# Identifying Multi Layers

**Identifying Multi Layer Stands**

Some stands can have 2 layers and still be considered even aged:

| Layers | Classed as | Reason |
|:--|:--|:--|
|pole:sapling | single | layers are similar |
| sapling:regen | single | layers are similar |

Others are identified as Multi


| Layers | Classed as | Reason |
|:--|:--|:--|
| even:pole:sampling:regen | multi | muti[ple layer types |
| mature:pole:sapling | multi | muti[ple layer types |
| mature:pole:sapling:regen | multi | muti[ple layer types |
| mature:pole:regen | multi | muti[ple layer types |
| mature: sapling:regen| multi | muti[ple layer types |
|pole:sapling:regen | multi | muti[ple layer types |

___

Can have 2 different layer types but still be considered even aged.   
in both cases, the disparity between the layers is not considered enough to class as multi.    
Tend to be small trees.    

If someone can pre-identify where we are managing for uneven, then these can be excluded from the MSYT generation.    

Where multiple layers are evident, treat these as multi-cohort  

These types of openings are identified to the analyst for a decision on how to determine yields  
