# Validation: Plant Natural

**Validation of Input data **




| # Features	| Stand Type	|
|:--|:--|
|410	| Managed Review: FC incomplete, Partially planted	|
|41	| Managed Review: FC incomplete, Planted invalid density	|
|3,531	| Managed Review: FC valid data, Planted invalid density	|
|7,714	| Managed Review: Not yet stocked	Natural |
|1	| Managed Review: FC no data - plant < 10%	|
|2,298	| Managed Review: FC incomplete - not planted	|
|58	| Managed Review: FC incomplete - plant < 10%	Natural |
|373	| Managed Review: FC low density, NOT planted	Natural |
|772	| Managed Review: FC Non Productive	Natural |
|3,771	|Review Reserve: all young in veg but has RC in FC	Natural |
|7,804	|Review Reserve: all old in veg	Natural |
|24,799	| Managed Review: Pre 1987, incomplete	|
|4	| Managed: Pre 1987, Missing future BEC Aggregate	| 
|88	| Managed Review: MISSING BEC, valid opening	Natural |
|105	| Managed Review: Missing BEC aggregate	|

___

After assessing Planted data and FC data can look for problem areas  

Assign these for the analyst to review.  

No species, no planted data, missing fc data  

And NO we don’t fix these.  We look for large problem areas.  IF that exists, we fix.  Otherwise, we identify these to be fixed for next round.  


